import { describe, expect, it } from 'vitest'
import {
  CoverageCandidateReportV1Schema,
  canonicalizeSourceLockV1,
  DistanceFeasibilityReportV1Schema,
  ExtendedSourceLockV1Schema,
  PRICECATCHER_TRANSFORM_VERSION,
  SourceLockV1Schema,
  SourceManifestV1Schema,
  validateDistanceFeasibilityReport
} from '../contracts'

const sha = 'a'.repeat(64)
const dates = (count: number) => Array.from({ length: count }, (_, index) => {
  const date = new Date(Date.UTC(2026, 7, 3 - count + index + 1))
  return date.toISOString().slice(0, 10)
})

const coverage = (scope: 'candidate-universe' | 'selected-content' = 'selected-content'): any => ({
  schemaVersion: 1,
  transformVersion: PRICECATCHER_TRANSFORM_VERSION,
  throughDate: '2026-08-03',
  sourceLockSha256: sha,
  scope,
  ...(scope === 'selected-content' ? { selectedContentDigests: { premises: sha, items: sha } } : {}),
  dataAsOfDate: '2026-08-03',
  calibrationDates: dates(14),
  premises: Array.from({ length: 10 }, (_, premise) => ({
    premiseCode: String(premise), officialName: `Premise ${premise}`, address: `Address ${premise}`,
    premiseType: 'market', state: 'Selangor', district: 'Petaling Jaya', distinctPresenceDates: 10,
    dateCoverageBasisPoints: 7142, completeItemCellCoverageBasisPoints: 7000, nearDaily: true
  })),
  items: Array.from({ length: 5 }, (_, item) => ({
    itemCode: String(item), officialName: `Item ${item}`, officialUnit: 'kg', itemGroup: 'food', itemCategory: 'fresh',
    coveredDates: 10, qualifyingPremiseCoverageDates: 10, qualifyingDateRateBasisPoints: 7142,
    meanPremiseCoverageBasisPoints: 7000, highCoverage: true
  })),
  passesCoverageCandidateGate: true,
  failureReasons: []
})

const distance = (): any => ({
  schemaVersion: 1,
  transformVersion: PRICECATCHER_TRANSFORM_VERSION,
  throughDate: '2026-08-03', sourceLockSha256: sha, dataAsOfDate: '2026-08-03',
  coverageReportSha256: sha, microzonesSha256: sha, premisesSha256: sha, itemsSha256: sha,
  referenceAndTargetDates: dates(60), targetDates: dates(30),
  finalPremiseCodes: Array.from({ length: 10 }, (_, index) => String(index)),
  finalItemCodes: Array.from({ length: 5 }, (_, index) => String(index)),
  microzones: [{
    microzoneId: 'central', premiseCount: 10,
    baselines: Array.from({ length: 10 }, (_, index) => ({ premiseCode: String(index), completeAlternativeDates: 21, completeAlternativeDateBasisPoints: 7000 })),
    minimumBaselineAlternativeDateBasisPoints: 7000, passes: true
  }],
  passesDeskDemoGate: true, failureReasons: []
})

const manifest = (url: string) => ({ url, retrievedAt: '2026-08-03T00:00:00.000Z', sha256: sha, byteLength: 1, rowCount: 1 })
const sourceLock = (analysisStartDate: string): any => ({
  schemaVersion: 1, sourceKind: 'synthetic-fixture' as const, throughDate: '2026-08-03', analysisStartDate, window: 'feasibility' as const,
  sources: [
    { role: 'item-lookup' as const, manifest: manifest('https://fixture.test/items.csv') },
    { role: 'transactions' as const, yearMonth: '2026-06', manifest: manifest('https://fixture.test/2026-06.csv') },
    { role: 'premise-lookup' as const, manifest: manifest('https://fixture.test/premises.csv') },
    { role: 'transactions' as const, yearMonth: '2026-07', manifest: manifest('https://fixture.test/2026-07.csv') },
    { role: 'transactions' as const, yearMonth: '2026-08', manifest: manifest('https://fixture.test/2026-08.csv') }
  ]
})

describe('feasibility contracts', () => {
  it('rejects self-certified coverage row metrics and derives the stable gate reasons', () => {
    // Break caught: a compiler can lie about nearDaily/highCoverage or pass with too few qualifying rows.
    const dishonest = coverage('candidate-universe')
    dishonest.premises[0].nearDaily = false
    dishonest.items[0].qualifyingDateRateBasisPoints = 7000
    dishonest.items[0].highCoverage = false
    expect(() => CoverageCandidateReportV1Schema.parse(dishonest)).toThrow()

    const sparse = coverage('candidate-universe')
    sparse.premises = sparse.premises.slice(0, 9)
    sparse.passesCoverageCandidateGate = false
    sparse.failureReasons = ['insufficient-near-daily-premises']
    expect(CoverageCandidateReportV1Schema.parse(sparse).failureReasons).toEqual(['insufficient-near-daily-premises'])
  })

  it('rejects an old selected-content transform while preserving a historical candidate report', () => {
    // Break caught: current selected evidence could be generated by a different transform.
    const selected = coverage()
    selected.transformVersion = '0.9.0'
    expect(() => CoverageCandidateReportV1Schema.parse(selected)).toThrow()
    const historical = coverage('candidate-universe')
    historical.transformVersion = '0.9.0'
    expect(CoverageCandidateReportV1Schema.parse(historical).transformVersion).toBe('0.9.0')
  })

  it('binds a distance report to its selected coverage rows and recomputes its desk gate', () => {
    // Break caught: a distance report can claim a final set or pass state unrelated to selected coverage.
    const selected = CoverageCandidateReportV1Schema.parse(coverage())
    const report = distance()
    expect(validateDistanceFeasibilityReport(report, selected).passesDeskDemoGate).toBe(true)
    expect(() => validateDistanceFeasibilityReport({ ...report, finalPremiseCodes: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '11'] }, selected)).toThrow()
    expect(() => DistanceFeasibilityReportV1Schema.parse({ ...report, microzones: [{ ...report.microzones[0], baselines: report.microzones[0].baselines.map((baseline: any, index: number) => index === 0 ? { ...baseline, completeAlternativeDateBasisPoints: 6999 } : baseline) }] })).toThrow()
  })

  it('derives selected-coverage-gate-failed only from its bound selected report', () => {
    // Break caught: a distance report can omit or invent the selected-coverage failure reason.
    const selected = coverage()
    selected.premises[0] = { ...selected.premises[0], distinctPresenceDates: 9, dateCoverageBasisPoints: 6428, nearDaily: false }
    selected.passesCoverageCandidateGate = false
    selected.failureReasons = ['insufficient-near-daily-premises']
    const report = { ...distance(), passesDeskDemoGate: false, failureReasons: ['selected-coverage-gate-failed'] }
    expect(validateDistanceFeasibilityReport(report, selected).failureReasons).toEqual(['selected-coverage-gate-failed'])
    expect(() => validateDistanceFeasibilityReport({ ...report, failureReasons: [] }, selected)).toThrow()
  })

  it('keeps the bootstrap feasibility lock exact and accepts earlier starts only through the explicit extended schema', () => {
    // Break caught: pre-selection bootstrap locks silently accept an unreviewed extended horizon.
    const bootstrap = sourceLock('2026-06-05')
    expect(SourceLockV1Schema.parse(bootstrap).analysisStartDate).toBe('2026-06-05')
    const extended = sourceLock('2026-06-04')
    expect(() => SourceLockV1Schema.parse(extended)).toThrow()
    expect(ExtendedSourceLockV1Schema.parse(extended).analysisStartDate).toBe('2026-06-04')
  })

  it('canonicalizes source-lock ordering and rejects impossible IMF-fixdates', () => {
    // Break caught: lock hashes could change with source ordering or accept a syntactically shaped impossible HTTP date.
    expect(canonicalizeSourceLockV1(sourceLock('2026-06-05')).sources.map(source => source.role)).toEqual([
      'transactions', 'transactions', 'transactions', 'premise-lookup', 'item-lookup'
    ])
    expect(() => SourceManifestV1Schema.parse({ ...manifest('https://fixture.test/data.csv'), lastModified: 'Tue, 31 Feb 2026 00:00:00 GMT' })).toThrow()
  })
})
